name: ouisync_app
description: OuiSync Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.5"
  flutter: ^3.3.2

dependencies:
  async: ^2.8.2
  auto_size_text: ^3.0.0
  badges: ^2.0.2
  biometric_storage: ^4.1.3
  bloc_test: ^9.0.3
  build_runner: ^2.1.7
  collection: ^1.16.0
  connectivity_plus: ^3.0.2
  cross_file: ^0.3.3
  cupertino_icons: ^1.0.4
  desktop_drop: ^0.4.1
  dns_client: ^0.2.1
  equatable: ^2.0.3
  external_path: ^1.0.1
  ffi: ^2.0.1
  file: ^6.1.4
  file_picker: ^5.2.5
  filesystem_picker: ^3.1.0
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6
  flutter:
    sdk: flutter
  flutter_background: ^1.2.0
  flutter_bloc: ^8.0.1
  flutter_file_dialog: ^2.3.0
  flutter_flavorizr: ^2.1.5
  flutter_hooks: ^0.18.2+1
  flutter_localizations:
    sdk: flutter
  flutter_loggy: ^2.0.1
  flutter_password_strength: ^0.1.6
  intl: ^0.17.0
  lecle_downloads_path_provider: ^0.0.2+6
  local_auth: ^2.1.2
  loggy: ^2.0.1+1
  mobile_scanner: ^2.0.0
  mockito: ^5.1.0
  move_to_background: ^1.0.2
  network_info_plus: ^3.0.1
  ouisync_plugin:
    path: ./ouisync-plugin
  package_info_plus: ^3.0.2
  path: ^1.8.2
  path_provider: ^2.0.9
  percent_indicator: ^4.2.2
  permission_handler: ^10.2.0
  qr_flutter: ^4.0.0
  r_get_ip: 
    git: https://github.com/J-Pabon/r_get_ip
  random_password_generator: ^0.2.1
  receive_sharing_intent: 
    git: https://github.com/J-Pabon/receive_sharing_intent
  result_type: ^0.2.0
  settings_ui: ^2.0.2
  share_plus: ^6.3.0
  shared_preferences: ^2.0.13
  styled_text: ^7.0.0
  system_tray: ^2.0.2
  tray_manager: ^0.1.8
  udp: ^5.0.3
  url_launcher: ^6.0.20
  window_manager: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.0.3
  # Use this command to generate internationalization files if you're not using
  # the vscode plugin:
  # # flutter pub run intl_utils:generate
  intl_utils: ^2.6.1
  lints: ^2.0.0
  msix: ^3.5.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Ouisync-icon-blue.ico
    - assets/add_with_qr.png
    - assets/nothing_here_yet.png
    - assets/locked_repo.png
    - assets/empty_folder.png
    # - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true

msix_config:
  display_name: OuiSync
  publisher_name: eQualitie
  certificate_path: .\certificates\self-signed\CERTIFICATE.pfx
  certificate_password: _ball$*watch17
  logo_path: .\assets\ouisync-beta-round-1200.png
  start_menu_icon_path: .\assets\ouisync-beta-round-1200.png
  tile_icon_path: .\assets\ouisync-beta-round-1200.png
  app_installer: #<-- app installer configuration
    publish_folder_path: .\installers
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: false
    capabilities: internetClient, internetClientServer, privateNetworkClientServer,
      removableStorage, documentsLibrary
  msix_version: 1.0.0.0

flavorizr:
  flavors:
    vanilla:
      app:
        name: 'OuiSync'

      android:
        applicationId: 'org.equalitie.ouisync'

      ios:
        bundleId: 'org.equalitie.ouisync'

    analytics:
      app:
        name: 'OuiSync'

      android:
        applicationId: 'org.equalitie.ouisync'
        firebase:
          config: './lib/firebase_options.dart'

      ios:
        bundleId: 'org.equalitie.ouisync'

    development:
      app:
        name: 'OuiSync-Dev'

      android:
        applicationId: 'org.equalitie.ouisync.dev'
        customConfig:
          versionNameSuffix: "\"-dev\""
        firebase:
          config: './lib/firebase_options.dart'

      ios:
        bundleId: 'org.equalitie.ouisync.dev'
