name: CI

on: 
  push:
    #branches: [master]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build_and_test:
    name: OuiSync Flutter App
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      # Download & install the Android SDK.
      - uses: malinskiy/action-android/install-sdk@release/0.1.2

      # Set up platform tools like adb.
      - run: sdkmanager platform-tools

      # Start ADB (and verify that pathing is working correctly).
      - run: adb devices

      # Verify $ANDROID_HOME is properly set for later Gradle commands.
      - run: echo $ANDROID_HOME
      - run: echo "y" | ls /Users/runner/android-sdk/
      - run: echo "y" | ls /Users/runner/android-sdk/cmdline-tools/
      - run: echo "y" | ls /Users/runner/android-sdk/cmdline-tools/latest/
      - run: echo "y" | ls /Users/runner/android-sdk/cmdline-tools/latest/bin/
      - name: Install NDK
        run: echo "y" | sudo /Users/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '2.5.2'
      - run: flutter pub get
      - run: flutter build apk --debug
      - uses: actions/upload-artifact@v1
        with:
         name: debug-apk
         path: build/app/outputs/apk/release/app-debug.apk
