name: CI

on:
  push:
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [master]

jobs:
  build_and_test:
    name: build and test on ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [android, linux, windows]
        include:
          - name: android
            os: ubuntu-latest
            target: aarch64-linux-android
            ndk:
              version: r25c
              abi: arm64-v8a
            test-env:
              OUISYNC_LIB: ouisync-plugin/ouisync/target/release/libouisync_ffi.so
            build-args: apk --target-platform android-arm64

          - name: linux
            os: ubuntu-latest
            analyze: true
            test-env:
              OUISYNC_LIB: ouisync-plugin/ouisync/target/release/libouisync_ffi.so
            build-args:

          - name: windows
            os: windows-latest
            test-env:
              OUISYNC_LIB: D:\a\ouisync-app\ouisync-app\ouisync-plugin\ouisync\target\release\ouisync_ffi.dll
            build-args:

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Add rust target
        run: rustup target add ${{ matrix.target }}
        if: matrix.target != ''

      - name: Install libfuse
        run: sudo apt-get install libfuse-dev
        if: matrix.name != 'windows'

      - name: Install Android NDK
        uses: nttld/setup-ndk@v1
        with:
            ndk-version: ${{ matrix.ndk.version }}
        if: matrix.ndk.version != ''

      - name: Set NDK ABI filter
        run: echo "ndk.abiFilters=${{ matrix.ndk.abi }}" >> android/local.properties
        if: matrix.ndk.abi != ''

      - name: Generate ./ouisync-plugin/ouisync/target/bindings.h
        run: |
         cd ouisync-plugin/ouisync
         cargo run --bin bindgen

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Run Flutter doctor
        run: flutter doctor -v

      - name: Get Flutter packages
        run:  dart pub get

      - name: Run Flutter code generators
        run: dart run build_runner build
        env:
          DSN:

      - name: Generate the Dart bindings for the Ouisync library
        run: cd ouisync-plugin && flutter pub run ffigen

      - name: Analyze
        run: |
          cd lib  && flutter analyze
          cd test && flutter analyze
          cd util && flutter analyze
        if: matrix.analyze == 'true'

      - name: Build Ouisync library for tests
        run: |
         cd ouisync-plugin/ouisync
         cargo build --release -p ouisync-ffi

      - name: Run tests
        run:
          flutter test
        env: ${{ matrix.test-env }}

      - name: Build Ouisync app
        run: flutter build ${{ matrix.build-args }}


