name: CI

on: 
  push:
    branches: [master]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build_and_test:
    name: OuiSync Flutter App
    runs-on: macos-11
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.2.3"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-java@v1
        with:
          java_version: $
      - uses: subosito/glutter-action@v1
        with:
          flutter_version: $
      - run: flutter pub get
      - run: flutter analyze
      